apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brain-service
  template:
    metadata:
      labels:
        app: brain-service
    spec:
      serviceAccountName: brain-service-account
      containers:
        - name: brain
          image: brain-service:local
          imagePullPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: brain-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: brain-role
rules:
  # Kopf requirements
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, get, watch]
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]
    
  # Watching & Restarting Deployment functionality
  - apiGroups: [""]
    resources: [pods]
    verbs: [list, watch, get, delete, patch]
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [list, watch, get, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: brain-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: brain-role
subjects:
  - kind: ServiceAccount
    name: brain-service-account
    namespace: default
